deployments:
  appName: ruby-challenge
  appVolumeMounts:
    - name: ruby-challenge-volume
      mountPath: /ruby-challenge
  appVolumes:
    - name: ruby-challenge-volume
      hostPath:
        path: /ruby-challenge
general:
  namespace: local-challenge
images:
  ruby: ruby:3.3.0
